
// This file has been generated by genreflex with the --capabilities option
static  const char* clnames[] = {
//--Begin classes
  "LCGReflex/CentralityTable",
  "LCGReflex/RPFlatParams",
  "LCGReflex/RPFlatParams::EP",
  "LCGReflex/std::vector<RPFlatParams::EP>",
  "LCGReflex/CentralityTable::CBin",
  "LCGReflex/std::vector<CentralityTable::CBin>",
  "LCGReflex/CentralityTable::BinValues",
//--End   classes
//--Final End
};

extern "C" void SEAL_CAPABILITIES (const char**& names, int& n )
{ 
  names = clnames;
  n = sizeof(clnames)/sizeof(char*);
}

